### ISSUE TITLE
Plexamp service doesn't appear to start 

### ISSUE THREAD

**Issue by nwpsys** [dustinrue/headless-plexamp#1]
Firstly - I have never used Github before, so if this is the wrong place for this sort of comment please feel free to move.

The install of headless-plexamp went along without an issue. However there is no Plexamp service running after "sudo systemctl enable plexamp" and performing the final reboot. When I try to start Plexamp manually again I get this error ...

pi@plexamp:~ $ node plexamp/js/index
Starting Plexamp.
DEVICE: No provider for source 8ea1d9bfabc799b28a092baf9083f5d187737bf8

When I entered my claim token I see a couple of errors in the log there which may or may not be important ... I'm not sure if any element of those logs need to remain private but happy to post them if OK to do so.

FYI I am using an Allo Digione HAT which works fine when I boot using a vanilla 64 bit Bullseye after I configure it.

FYI # 2 This is my first Pi project !

**Comment by dustinrue** [comment]
Thank you for giving it a try. I believe I know what I did wrong and will push up a new release that includes a fix. This release will also include the latest version of the beta. 

EDIT: Nothing I wrote will work, I'll figure out why it didn't load and post a fix

**Comment by dustinrue** [comment]
Also, congrats on your first Pi project! Have fun with it

**Comment by dustinrue** [comment]
I tested the most recent image that I build today and it is working perfectly for me. Please try that image and let me know if you run into any issues.

**Comment by nwpsys** [comment]
Thanks for all your effort on this, Dustin.

As it is a rainy day I have re-imaged / installed from scratch but now I get more obvious error messages when I claim the token.

pi@plexamp:~ $ node plexamp/js/index
Starting Plexamp.
Please visit https://plex.tv/claim and enter the claim token: claim-I-Guess-I-Should-Blank-This-Out
ACCOUNT: Refreshing data.
DEVICE: Initializing device manager.
DEVICE: Error loading resources.
DEVICE: Initializing manager.
DEVICE: Fetching latest provider list from cloud.
DEVICE: Fetching latest list from cloud.
DEVICE: Fetching latest cloud player list from https://sonos.plex.tv
DEVICE: No previous data, waiting for cloud data.
DEVICE: Fetched 4 devices from the cloud.
DEVICE: Error loading cloud players from plex.tv HTTP status 403
DEVICE: Persisting 4 devices.
DEVICE: Starting connection test.
DEVICE: Looking for an active server in 1 total servers.
DEVICE: Finding best connection for MEDIA-NUC 8ea1d9bfabc799b28a092baf9083f5d187737bf8.
DEVICE: Server connection worked for MEDIA-NUC ~ https://192-168-1-101.3d9e54765e0b422d85e617fa67786b9f.plex.direct:32400
DEVICE: Reading libraries and features from MEDIA-NUC
DEVICE: Server connection worked for MEDIA-NUC ~ https://my.static.ip.address.was.here.3d9e54765e0b422d85e617fa67786b9f.plex.direct:27043
DEVICE: Found 7 libraries from MEDIA-NUC: Home, Movies, TV Shows, Music, BLURAY Test, Motorsport, Playlists
DEVICE: Got working server of MEDIA-NUC
DEVICE: Finding best connection for Chrome l8w08egfdvahszgnynuve6fq.
DEVICE: Finding best connection for Android da0f97b5-514d-4f21-b477-ae434b21f37d.
DEVICE: Finding best connection for TV 2021 yhn2ud038jqti6gl9f4of8ri.
DEVICE: Persisting 4 devices.
DEVICE: Initialization finished in 1692ms.
Setting server and library to: 8ea1d9bfabc799b28a092baf9083f5d187737bf8 /library/sections/1
Switching server: 8ea1d9bfabc799b28a092baf9083f5d187737bf8 /library/sections/1
Server Activity: Connecting based on switch.
Server Activity: Trying to connect to 8ea1d9bfabc799b28a092baf9083f5d187737bf8.
USER: Refreshing users.
APP: Sign in complete ac918e39-c65d-4b9b-839d-381d08887f5a 2849470
DEVICE: The player l8w08egfdvahszgnynuve6fq wasn't found in available resources at https://192-168-1-101.3d9e54765e0b422d85e617fa67786b9f.plex.direct:32400.
DEVICE: The player l8w08egfdvahszgnynuve6fq wasn't found in available resources at https://my.static.ip.address.was.here.3d9e54765e0b422d85e617fa67786b9f.plex.direct:27043.
DEVICE: Connection testing failed for Chrome
DEVICE: The player yhn2ud038jqti6gl9f4of8ri wasn't found in available resources at https://192-168-1-101.3d9e54765e0b422d85e617fa67786b9f.plex.direct:32400.
DEVICE: The player yhn2ud038jqti6gl9f4of8ri wasn't found in available resources at https://my.static.ip.address.was.here.3d9e54765e0b422d85e617fa67786b9f.plex.direct:27043.
DEVICE: Connection testing failed for TV 2021

This looks to be more of a Plex issue rather than your image ?

**Comment by nwpsys** [comment]
Actually I think the problems are more at my end. I'll close this for now while I work some more on it.
